### ISSUE TITLE
Not normal enough

### ISSUE THREAD

**Issue by VeiledProduct80** [insertish/TotallyNormalRepository#1] opened 2022-05-27 10:54 UTC
![Ttea4TgzYvZjIm0AJMVH0uiD0J5hpT4yLu5us6GZxz](https://user-images.githubusercontent.com/71269275/170686370-ecb89b60-18ca-47b8-ab5e-a4b997b33af4.gif)

**Comment by insertish** [comment] 2022-06-20 00:00
Duplicate of https://github.com/insertish/TotallyNormalRepository/issues/2

**Closed as not planned by insertish** 2022-06-20 00:00 UTC
